apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server-go-dm
  namespace: user-server-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-server-go
  template:
    metadata:
      name: user-server-go-pod
      labels:
        app: user-server-go
    spec:
      containers:
        - name: user-server-go
          image: /user-server-go/user-server-go:latest
          # If using a local image, use Never, default is Always
          #imagePullPolicy: Never
          command: ["./user_server_go", "-c", "/app/configs/user_server_go.yml"]
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          volumeMounts:
            - name: user-server-go-vl
              mountPath: /app/configs/
              readOnly: true

          ports:
            - name: http-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              port: http-port
              path: /health
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: http-port
              path: /health

            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      # todo for private repositories, you need to create a secret (here docker-auth-secret) to store the account and password to log into docker
      imagePullSecrets:
        - name: docker-auth-secret
      volumes:
        - name: user-server-go-vl
          configMap:
            name: user-server-go-config
